salesforce-app/src/objects/Custom_Object_2__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Object 2</relationshipLabel>
        <relationshipName>Custom_Object_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Object 2</label>
    <nameField>
        <label>Custom Object 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Object 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-app/src/classes/TestClass.cls
@isTest
public class TestClass {
    static testMethod void testController() {
        Contact contactInsatnce = new Contact(LastName = 'Test');
        insert contactInsatnce;
        System.assertEquals(1, TestController.fetchContactList().size());
    }
    
    static testMethod void testObject2Trigger() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        System.assert(acc.Id != null);
        
        Custom_Object_2__c instance = new Custom_Object_2__c (Name='test', Account__c = acc.Id);
        insert instance;
    } 

}